"""
Load hierarchical courses into Redis.

This script loads courses generated by generate_hierarchical_courses.py
into the two-tier Redis storage (summaries + details).

Usage:
    # Load courses (appends to existing data)
    python -m redis_context_course.scripts.load_hierarchical_courses \
        -i src/redis_context_course/data/hierarchical/hierarchical_courses.json

    # Force reload (clears existing data first)
    python -m redis_context_course.scripts.load_hierarchical_courses \
        -i src/redis_context_course/data/hierarchical/hierarchical_courses.json \
        --force
"""

import asyncio
import json
import click
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

from redis_context_course.hierarchical_models import (
    CourseSummary,
    CourseDetails,
    HierarchicalCourse,
)
from redis_context_course.hierarchical_manager import HierarchicalCourseManager
from redis_context_course.redis_config import redis_config


def clear_existing_data(summary_index: str, details_prefix: str):
    """Clear existing course data from Redis."""
    redis_client = redis_config.redis_client

    # Clear summary keys
    summary_keys = redis_client.keys(f'{summary_index}:*')
    if summary_keys:
        for key in summary_keys:
            redis_client.delete(key)
        print(f"   Deleted {len(summary_keys)} summary keys")

    # Clear detail keys
    detail_keys = redis_client.keys(f'{details_prefix}:*')
    if detail_keys:
        for key in detail_keys:
            redis_client.delete(key)
        print(f"   Deleted {len(detail_keys)} detail keys")

    # Drop the index
    try:
        redis_client.execute_command('FT.DROPINDEX', summary_index)
        print(f"   Dropped index: {summary_index}")
    except Exception:
        pass  # Index may not exist

    return len(summary_keys), len(detail_keys)


async def load_courses_from_json(json_file: Path, manager: HierarchicalCourseManager):
    """Load courses from JSON file into Redis."""
    
    print(f"📖 Loading courses from {json_file}...")
    
    with open(json_file, 'r') as f:
        data = json.load(f)
    
    courses_data = data.get("courses", [])
    print(f"Found {len(courses_data)} courses in file")
    
    loaded = 0
    failed = 0
    
    for course_data in courses_data:
        try:
            # Reconstruct HierarchicalCourse
            summary = CourseSummary(**course_data["summary"])
            details = CourseDetails(**course_data["details"])
            
            course = HierarchicalCourse(
                id=course_data["id"],
                summary=summary,
                details=details,
                created_at=datetime.fromisoformat(course_data["created_at"]),
            )
            
            # Add to Redis
            success = await manager.add_course(course)
            if success:
                loaded += 1
                if loaded % 10 == 0:
                    print(f"  Loaded {loaded}/{len(courses_data)} courses...")
            else:
                failed += 1
                
        except Exception as e:
            print(f"  ❌ Error loading course: {e}")
            failed += 1
    
    print(f"\n✅ Loading complete!")
    print(f"   Loaded: {loaded}")
    print(f"   Failed: {failed}")
    
    return loaded, failed


@click.command()
@click.option(
    '--input-file',
    '-i',
    type=click.Path(exists=True),
    required=True,
    help='JSON file with hierarchical courses'
)
@click.option(
    '--summary-index',
    '-s',
    default='course_summaries',
    help='Name for summary vector index'
)
@click.option(
    '--details-prefix',
    '-d',
    default='course_details',
    help='Prefix for details hash keys'
)
@click.option(
    '--force',
    '-f',
    is_flag=True,
    default=False,
    help='Clear existing data before loading (force reload)'
)
def main(input_file: str, summary_index: str, details_prefix: str, force: bool):
    """Load hierarchical courses into Redis.

    By default, appends to existing data. Use --force to clear existing
    data before loading (useful when course data has been regenerated).
    """

    print("🚀 Hierarchical Course Loader\n")

    # Clear existing data if force flag is set
    if force:
        print("🗑️  Clearing existing data (--force flag set)...")
        summaries_deleted, details_deleted = clear_existing_data(summary_index, details_prefix)
        print(f"   ✅ Cleared {summaries_deleted} summaries and {details_deleted} details\n")

    # Create manager
    manager = HierarchicalCourseManager(
        summary_index_name=summary_index,
        details_prefix=details_prefix,
    )

    # Ensure index is created before loading data
    manager._get_summary_index()

    # Load courses
    input_path = Path(input_file)
    loaded, failed = asyncio.run(load_courses_from_json(input_path, manager))

    if loaded > 0:
        print(f"\n📊 Redis Storage:")
        print(f"   Summary index: {summary_index}")
        print(f"   Details prefix: {details_prefix}")
        print(f"\n💡 You can now use HierarchicalCourseManager to search courses!")


if __name__ == "__main__":
    main()

