version: '3'
services:
  docs:
    image: httpd:2.4.63
    container_name: docs
    environment:
      - VM_HOST=${HOSTNAME}
      - HOST_IP=${HOST_IP}  
      - DOMAIN=${DOMAIN}
    ports:
      - '80:80'
    volumes:
      - './dist/client:/usr/local/apache2/htdocs/'
      - './httpd.conf:/usr/local/apache2/conf/httpd.conf'
    depends_on:
      litellm:
        condition: service_started

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: litellm
      POSTGRES_PASSWORD: password
      POSTGRES_DB: litellm
      POSTGRES_HOST_AUTH_METHOD: trust

  litellm:
    image: ghcr.io/berriai/litellm:main-v1.68.0-stable
    container_name: litellm
    environment:
      DATABASE_URL: postgres://litellm:password@postgres:5432/litellm
      STORE_MODEL_IN_DB: "true"
      GOOGLE_APPLICATION_CREDENTIALS: /app/sa.json
      OPENAI_API_KEY: ${GENAI_WKSHP_OPENAI_API_KEY}
      LITELLM_ENABLE_CORS: "true"
    ports:
      - "4000:4000"
    volumes:
      - ./litellm_config.yaml:/app/config.yaml
      - ./vertex_sa.json:/app/sa.json
    depends_on:
      - postgres
    command: --config /app/config.yaml --detailed_debug

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.16.21.0/24
          gateway: 172.16.21.1

