const id = "intro/welcome.mdx";
						const collection = "docs";
						const slug = "intro/welcome";
						const body = "\nWelcome to Context Engineering with Redis & LangChain. We are excited to help you master the art of building production-ready AI agents with proper context management. This lab will take you from basic RAG pipelines all the way to building a fully-featured ReAct agent with memory. Before diving in, check out some important details below that will set your expectations for the lab experience.\n\n### Lab structure\nThe lab will take place in a Jupyter Notebook environment (you'll open it in the next section), which provides an interactive way to learn and experiment with the concepts covered in this lab.\n\nThere are three sections as part of this lab:\n\n1. **Context Engineering Foundations**: This section introduces you to the fundamentals of context engineering—what it is, why it matters, and how to craft effective system prompts. You'll observe a baseline RAG agent and then apply data engineering techniques to dramatically reduce token usage while maintaining quality.\n2. **From Pipeline to Agent**: In this section, you'll transform a simple RAG pipeline into a true LangGraph-based agent with intent classification, hierarchical retrieval, hybrid search, and the ReAct (Reasoning + Acting) architecture for transparent decision-making.\n3. **Memory Context**: In the final section, you'll add Redis Agent Memory Server for working and long-term memory (cross-session persistence) and learn how to manage memory context effectively.\n\n### Learning objectives \n\nBy the end of this lab, you will be able to: \n- Familiarity with the four pillars of context and how to engineer them effectively\n- Craft system context by creating effective system prompts that define agent behavior and capabilities\n- Optimize a RAG agent it using basic data engineering techniques\n- Improve retrieved context intelligently using hierarchical retrieval, intent classification, and hybrid search\n- Transform a RAG pipeline into a ReAct agent with transparent reasoning traces\n- Integrate working memory and long-term memory for intelligent multi-turn conversations\n\n### Lab environment resources\n\nBelow you'll find all the resources that come with this lab. We recommend opening <a href=\"http://localhost:5540/\" target=\"genai_insight\">Redis Insight</a> alongside the Jupyter Notebook to help you visualize and explore the data stored in Redis throughout the lab.\n\n<div>\n| Resource                                                     | Details                                                        |                                                 \n| ------------------------------------------------------------ | ------------------------------------------------------------ |\n| <a href=\"http://localhost:10889/lab/tree/work/materials\" target=\"jupyter\">Jupyter Notebook</a>  | A Jupyter Notebook that hosts all the labs       |\n| <a href=\"http://localhost:5540/\" target=\"genai_insight\">Redis Insight</a> | Redis GUI tool           |\n</div>\n";
						const data = {title:"Welcome",editUrl:true,head:[],template:"doc",sidebar:{order:1,hidden:false,attrs:{}},pagefind:true,draft:false};
						const _internal = {
							type: 'content',
							filePath: "/Users/nitin.kanukolanu/workspace/lab-contexteng/src/content/docs/intro/welcome.mdx",
							rawData: undefined,
						};

export { _internal, body, collection, data, id, slug };
